- src/App.js
- src/components/ExpensesForm/ExpensesForm.js
- src/components/ExpensesSplit/ExpensesSplit.js
- src/components/NavBar/NavBar.js
- src/components/NavBar/SignInDialog.js
- src/pages/expenses/ExpensesPage.js
- set up some base code before implementing a new feature for the expense 
- Fix some errors for logging in in, which it show 2 buttons for log in and fix issues with open prop of the component being undefined
> set up base for expense split and fix some small alex codes' errors

- frontend/src/components/ItineraryForm/ItineraryAccordion.js
- frontend/src/pages/itinerary/ItineraryPage.js
Added the files ItineraryAccordion.js and ItineraryPage.js.
In ItineraryPage.js, we can:
Created the ability to click into days using a MUI accordion component.
Created the ability to click into specific activities using a MUI accordion component.
Add activities within each individual day.
Edit activities within each individual day.
Remove activities within each individual day.
Add additional days.
Confirm removal of activities with a MUI dialog popup.
TODO:
Be able to remove days.
Make the prompt for adding activities include start times, and end times.
Turn the prompt for editing activities into a new MUI dialog popup.
Be able to dynamically place new activities sequentially according to their time slots.
Make the itinerary page look more professional.
> Created a barebones implementation of the itinerary page

- frontend/src/components/GoogleMapBlock/GoogleMapBlock.js
- frontend/src/pages/map/MapPage.js
I updated the Google Maps block to do a couple of things. Add the ability to add markers to the map (Which includes info windows and names for the markers), as well as introduce the ability to change the map center location and size of the map block. Documentation for it will soon follow in a later pull request.
> Update the Google Maps Block

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-development-enhancement.md
Created the issues template for Bug Issues and Feature Enhancements. This allows everyone to be more descriptive with Bug reports as well as Feature Enhancements.
> Update issue templates

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ItineraryForm/Activity.css
- frontend/src/components/ItineraryForm/Activity.jsx
- frontend/src/components/ItineraryForm/ItineraryAccordion.js
- frontend/src/pages/itinerary/ItineraryPage.js
- frontend/yarn.lock
---
name: "Drag and Drop Feature Addition"
about: "Adding a drag and drop feature to itinerary page"
title: "feat: "
labels: "enhancement, not-reviewed"
assignees: ""
---
Using [dnd-kit](https://docs.dndkit.com/) for react, I implemented drag and drop features for each of the activities that are listed. The items can be dragged and dropped within each day of the activity
Fixes #40
> Drag and drop feature added to activities in itinerary page

- .gitignore
---
name:  Fixed Master branch .gitignore
about: Fix a .gitignore mistake
---
Removed the package.json from the .gitignore file.
> Update .gitignore EMERGENCY

- .github/workflows/Format.yml
---
name: "Updating Format Workflow File"
---
Update the workflow file to include formatting for both front-end and backend code including Go (Golang)
Fixes #93
> Updating the Format Workflow file by adding a formatter for Go

- frontend/src/components/FriendsPage/AddRemoveFriends.js
- frontend/src/components/FriendsPage/FriendsContainer.js
- frontend/src/pages/friends/FriendsPage.js
---
name: "Included multiple comments for documentation on Friends page code"
about: "Adds documentation to Friend Page related code"
title: "feat: "
labels: "Documentation"
assignees: ""
---
This PR includes additional comments throughout my code in multiple files related to code for the Friends Page. The purpose of this is to explain what is going on in my code for ease of readability and understanding.
> Included multiple comments for documentation on Friends page code

- frontend/package.json
- frontend/src/components/GatheringInfo/SearchBar.js
Adding functionality to the search bar via API call. Using API Ninjas to fetch data, which will show up in a dropdown menu as users type in their destination.
> Adding functionality to search bar

- frontend/src/_tests_/SignUpForm.test.jsx
- frontend/src/_tests_/ToggleTheme.test.jsx
Created a simple Unit test for the ToggleTheme component and the Signup component. This was a bit more complex than intended and needs to be revisited in the future to test out creating a profile through the page however I need to make contact with William to check if he would like that to be tested in the backend rather than the front end. It only test the value of the text block for the username but can be expanded on later. The ToggleTheme just ensures the toggle button renders which would allow the theme to be toggled.
Fixes #114
> Jordan toggle theme unit test

- frontend/src/components/NavBar/NavBar.js
- frontend/src/css/GatheringInfo.css
This pull request verifies if a user is logged in to correctly display the right pages. If user does not have an account, only two pages are available. If user does, then our other features show up.
> Nav bar Authentication

- frontend/src/components/GettingStarted/LocationImage.js
This creates a component that stores an image, a label for the name, and latitude/longitude values for use with the map. It is currently set to link to the /maptemp, but this can be changed to any page it is needed in.
Fixes # (issue)
> Image Component for GettingStarted page

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ItineraryForm/Activity.css
- frontend/src/components/ItineraryForm/Activity.js
- frontend/src/components/ItineraryForm/ItineraryAccordion.js
- frontend/src/pages/itinerary/ItineraryPage.js
The activities listed on the itinerary page did not have a sense of time, thus adding a timeline view allows users to easily understand their schedule of the day. 
Fixes #100
> Activity display to timeline view

- frontend/src/components/GatheringInfo/SearchBar.css
- frontend/src/components/GatheringInfo/SearchBar.js
Updating the search bar dropdown that Amai83 created. Due to a rollback of the repository when we had an issue with certain files being added/deleted when they weren't supposed to, this feature was removed however It is needed for the getting info page and adds some working features to the product. It was originally created by Amai83 and used API Ninjas Cities for getting city names, however, there would sometimes be duplicates that might have caused confusion so instead I used the open street map API. I did want to use the Google Places API however some of the documentation is lacking and I was having some issues attempting to get all the information needed to use it. In the future I plan on updating it in order to us the Google Places API, however for now I will just start with the the …
> updating SearchBar.css and SearchBar.js to allow auto complete

- docs/Design_Diagram/AI_Document/ExpensePage.md
- frontend/src/components/Expense2.0/Activity.js
- frontend/src/components/Expense2.0/AddExpense.js
- frontend/src/components/Expense2.0/DataGen.js
- frontend/src/components/Expense2.0/ExpenseDashBoard.js
- frontend/src/components/Expense2.0/History.js
- frontend/src/components/Expense2.0/Overview.js
- frontend/src/pages/expenses/ExpensesPage.js
This update brings several improvements and refactoring to the expense management system, aiming to enhance user experience and code maintainability. Notable changes include integrating a more streamlined interface, introducing functionality enhancements in expense splitting, and various bug fixes.
- **UI Simplification:** Merged four tabs into a single 'All' tab for a cleaner interface.
- **Add Expense Improvements:**
- Set the default split option to 'No Split' and disable user selection when splitting is not applicable.
- Refactored the Add Expense form into smaller functions to facilitate easier maintenance.
- **New Features:**
- Added the ability to opt out of splitting expenses directly from the UI.
- Implemented auto-generated IDs for expenses to resolve conflicts effectively.
- …
> Hot fixes for expense ( bunch of hot fixes) 

- frontend/src/components/ItineraryForm/DatePickerComponent.js
- frontend/src/utils/LocalStorageManager.js
This PR includes an error check for parsing data in getFromLocal to prevent issues with parsing undefined values. Values could be set from previous instances or not set at all, causing runtime errors when the application was started.
> JSON Parse Error Check

- frontend/src/_tests_/DateAvailability.test.jsx
- frontend/src/components/GatheringInfo/DateAvailability.css
- frontend/src/components/GatheringInfo/DateAvailability.js
- frontend/src/css/PollPage.css
- frontend/src/pages/getting_started/PollPage.js
This pull request includes the unit testing necessary in order to greatly increase the test coverage of the DateAvailability component. With these unit tests in place, the possibility of page-breaking bugs/glitches affecting users lowers greatly. These unit tests were able to achieve 80% coverage on code statements, which covers a large majority of the component's fundamental functionalities. This pull request also strived to document the DateAvailability component much more in-depth. Not only was the documentation more in-depth, but the documentation also provides more transparent insight on the use of AI on the component.
Fixes #154
Fixes #155
> DateAvailability Unit Tests + AI Documentation

- frontend/src/_tests_/AddRemoveFriends.test.jsx
- frontend/src/_tests_/BoxFriend.test.jsx
- frontend/src/_tests_/SearchBarGather.test.jsx
- frontend/src/_tests_/SearchTrip.test.jsx
This pull request contain unit test files for I AddRemoveFriend, BoxFriend, SearchBar in the gather component, and Search Trip files and all of the result are at least 80% or more
Fixes # (issue)
Coming soon 
Coming soon
> Add more unit tests for some short code files

- frontend/package.json
- frontend/src/_tests_/SignInPopUp.test.jsx
This PR fixes a previous merge conflict
More unit tests for:
- SignInPopUp.js
> More unit tests and hot fix for package.json

- frontend/src/_tests_/SignInDialog.test.jsx
Added test coverage for SignInDialog.js
> Added unit Testing for SignInDialog.js

- frontend/src/App.js
- frontend/src/pages/Auth_Pages/LogoutPage.js
Please include a summary of the changes and the related issue.
Fixes # (issue)
> Added logout page and clear catch

- frontend/src/components/ItineraryForm/Activity.js
- frontend/src/css/Activity.css
- frontend/src/pages/itinerary/ItineraryPage.js
Updates on the location input for the create event dialog.
Also fixing module not found error of a file that was not finished implementing
Fixes # N/A
> Location input UI update + module not found error fix
